// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package hs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import structpb "google.golang.org/protobuf/types/known/structpb"
import timestamppb "google.golang.org/protobuf/types/known/timestamppb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NamedStruct struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Definition           *structpb.Struct       `protobuf:"bytes,2,opt,name=definition" json:"definition,omitempty"`
	LastModified         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NamedStruct) Reset()         { *m = NamedStruct{} }
func (m *NamedStruct) String() string { return proto.CompactTextString(m) }
func (*NamedStruct) ProtoMessage()    {}
func (*NamedStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_875aade9fbee2630, []int{0}
}
func (m *NamedStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamedStruct.Unmarshal(m, b)
}
func (m *NamedStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamedStruct.Marshal(b, m, deterministic)
}
func (dst *NamedStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamedStruct.Merge(dst, src)
}
func (m *NamedStruct) XXX_Size() int {
	return xxx_messageInfo_NamedStruct.Size(m)
}
func (m *NamedStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_NamedStruct.DiscardUnknown(m)
}

var xxx_messageInfo_NamedStruct proto.InternalMessageInfo

func (m *NamedStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NamedStruct) GetDefinition() *structpb.Struct {
	if m != nil {
		return m.Definition
	}
	return nil
}

func (m *NamedStruct) GetLastModified() *timestamppb.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func init() {
	proto.RegisterType((*NamedStruct)(nil), "testproto.NamedStruct")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_875aade9fbee2630) }

var fileDescriptor_test_875aade9fbee2630 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x29, 0x99, 0xf4, 0xfc,
	0xfc, 0xf4, 0x9c, 0x54, 0x7d, 0x30, 0x2f, 0xa9, 0x34, 0x4d, 0xbf, 0xb8, 0xa4, 0xa8, 0x34, 0x19,
	0xaa, 0x50, 0x4a, 0x1e, 0x5d, 0xb6, 0x24, 0x33, 0x37, 0xb5, 0xb8, 0x24, 0x31, 0xb7, 0x00, 0xa2,
	0x40, 0x69, 0x36, 0x23, 0x17, 0xb7, 0x5f, 0x62, 0x6e, 0x6a, 0x4a, 0x30, 0x58, 0x9b, 0x90, 0x10,
	0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0x64,
	0xce, 0xc5, 0x95, 0x92, 0x9a, 0x96, 0x99, 0x97, 0x59, 0x92, 0x99, 0x9f, 0x27, 0xc1, 0xa4, 0xc0,
	0xa8, 0xc1, 0x6d, 0x24, 0xae, 0x07, 0x31, 0x59, 0x0f, 0x66, 0xb2, 0x1e, 0xc4, 0x80, 0x20, 0x24,
	0xa5, 0x42, 0xf6, 0x5c, 0xbc, 0x39, 0x89, 0xc5, 0x25, 0xf1, 0xb9, 0xf9, 0x29, 0x99, 0x69, 0x99,
	0xa9, 0x29, 0x12, 0xcc, 0x60, 0xbd, 0x52, 0x18, 0x7a, 0x43, 0x60, 0xae, 0x0a, 0xe2, 0x01, 0x69,
	0xf0, 0x85, 0xaa, 0x77, 0x62, 0x89, 0x62, 0xca, 0x28, 0x4e, 0x62, 0x03, 0xab, 0x33, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x9e, 0x1a, 0x66, 0xc3, 0x02, 0x01, 0x00, 0x00,
}
